# Generated by Django 4.0.2 on 2022-02-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_alter_contacto_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='gestionado',
            field=models.BooleanField(default=False),
        ),
    ]
