# Generated by Django 4.0.2 on 2022-02-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleta', '0002_alter_boleta_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='boleta/uploads/'),
        ),
    ]
