# Generated by Django 4.0.2 on 2022-02-20 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_alter_post_fecha_publicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=80)),
                ('telefono', models.IntegerField()),
                ('responsabilidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.responsabilidad')),
            ],
        ),
    ]
