# Generated by Django 4.0.2 on 2022-02-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_responsabilidad_voluntario'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='nombre',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
